### PR TITLE
fix #27 add mkdir -p options for open methods

### LINKED ISSUE #27: HPSS mkdir -p
### Pacifica Archive Interface version
master
### Pacifica Core Software versions
master
### Platform Details
Any
### Scenario:
Seems there's a mkdir -p needing to be done for hpss files. Using large file IDs we need to mkdir -p on the hpss side to make sure the parent directory is created before opening the file.
### Steps to Reproduce:
1. configure archive interface with hpss
1. try a PUT using a large number `curl -X PUT -T blah localhost:8080/12345`
### Expected Result:
should have worked
### Actual Result:
Seems HPSS is returning an unable to open file.

### PR DESCRIPTION
**Pull request by dmlb2000**
### Description

This adds mkdir -p options to allow for creating more complex paths.
### Issues Resolved

#27 
### Check List

- [x] All tests pass. See <https://github.com/pacifica/pacifica-docs/blob/master/development/TESTING.md>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by dmlb2000** [comment]
@ChristopherKnight If you could take a look at this that would be good.

**Comment by ChristopherKnight** [comment]
Things looked pretty good to me:

C extentsion for HPSS seemed like it had the correct bits happening.  
POSIX file is now using config file to see if using id2filename algorithm

Question i have:

Why is id2filename in posix using a lambda function? Seems like you could just pass the id and get the result with a simple function call

**Comment by dmlb2000** [comment]
@ChristopherKnight I wanted the id2filename to be optional for posix backend. The lambda methods were used to reduce the cyclomatic complexity, if those weren't there the logic would have to be put into the open method to switch around using id2filename or not... Does that make sense?

**Comment by ChristopherKnight** [comment]
Yes that makes sense.  while i think it makes it harder to read, i understand keeping the cyclomatic complexity down

**Review by ChristopherKnight — COMMENTED** [review]
I suggest merging with the iss_16 branch which deals with file permissions.  There will be some conflicts dealing with file paths that should be easy to resolve, but will be necessary.

**Pull request merged**
